name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # 获取代码 <button class="citation-flag" data-index="2"><button class="citation-flag" data-index="6">

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # 根据项目需求调整JDK版本 <button class="citation-flag" data-index="6"><button class="citation-flag" data-index="8">
        distribution: 'temurin'

    - name: Setup Android environment
      uses: android-actions/setup-android@v3
        
    - name: Build Android APK
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease --stacktrace # 执行构建命令 <button class="citation-flag" data-index="4"><button class="citation-flag" data-index="5"><button class="citation-flag" data-index="7">
      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/*.apk  # 上传构建产物 <button class="citation-flag" data-index="4"><button class="citation-flag" data-index="5">
